---
apiVersion: v1
kind: Service
metadata:  
  name: catalogue
  namespace: roboshop 
  labels:
    env: dev
    component: catalogue
    project: roboshop

spec:
  selector:
    env: dev
    component: catalogue
    project: roboshop
  ports:
    - targetPort: 8080 
      port: 8080
      protocol: TCP

      
      



